name: Sync to Hugging Face hub


on: 
  push:
  schedule: 
  - cron: "0 0 * * *"


  # to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://Juneyy:$HF@huggingface.co/spaces/juneyy/PredictTemp30Days
